services:
#  api-gateway:
#    build:
  notification-rabbitmq-handler:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      -
  notification-mgmt-service:
    build: ./Notificationmanagement-service
    container_name: notification-mgmt-service
    ports:
      - "8080:8080"